[package]
name = "mmu_lib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow  = { workspace = true				}
log	= { workspace = true				}
ram_lib = { path = "../ram_lib"				}
tokio	= { workspace = true, features = ["full"]	}	